#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026-present the Unsloth AI Inc. team. All rights reserved.

"""Fails when `exec`/`eval`/`compile` is handed a string built by interpolation.

The pattern this exists for is the one PR unslothai/unsloth-zoo#1083 removed:

    exec(f"import transformers.models.{model_type}.modeling_{model_type}")

`model_type` came off a downloaded config.json, so a hostile model repo reached an
`exec`. Bare `exec(source)` where `source` is generated by `inspect.getsource` is
normal and heavily used here, so it is NOT flagged - what is flagged is a first
argument that is an f-string, a string concatenation, a `%` format or a `.format()`
call, because that is the shape where a value becomes syntax.

Reviewed exceptions live in `dynamic_exec_allowlist.json` next to this file. Entries
are keyed on (path, enclosing qualname, sha256 of the normalised call source) rather
than a line number, so they survive edits elsewhere in the file but not edits to the
call itself: change the call and you have to re-justify it.

Stdlib only, so it can run in a lint job that installs nothing.

Usage:
    python scripts/lint_dynamic_exec.py                 # check the package
    python scripts/lint_dynamic_exec.py --self-test     # check the checker
    python scripts/lint_dynamic_exec.py --update        # rewrite the allowlist
    python scripts/lint_dynamic_exec.py --paths a.py b.py
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import re
import sys
import warnings
from pathlib import Path


SINKS = ("exec", "eval", "compile")

REPO_ROOT = Path(__file__).resolve().parents[1]
ALLOWLIST_PATH = Path(__file__).resolve().parent / "dynamic_exec_allowlist.json"

# Directories scanned by default. Tests are excluded: they legitimately keep the
# removed exec/eval around as an oracle to prove the replacement matches it.
# `unsloth-cli.py` is a tracked entrypoint that the adjacent compile and ruff steps
# already cover; leaving it out meant an interpolated call added there was never
# visited by the security gate at all.
DEFAULT_TARGETS = (
    "unsloth",
    "studio",
    "unsloth_cli",
    "scripts",
    "cli.py",
    "unsloth-cli.py",
)


class ScanError(Exception):
    """A file the checker could not finish reading. The gate fails rather than guess."""


def _relative(path: Path) -> str:
    """Repo-relative where possible; absolute for the self-test's temp files.

    Always forward slashes: the allowlist is committed, and a Windows checkout that
    regenerated it with backslashes would rewrite every entry.
    """
    try:
        return path.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


# Methods that build a string out of values. `format_map` is `format` with the
# fields taken from a mapping instead of keyword arguments - same interpolation,
# same shape, so leaving it out let `exec("import {m}".format_map(cfg))` through.
_BUILDERS = ("format", "format_map", "join")

# Conversions that hand the same source on in another type. `exec`, `eval` and
# `compile` all accept bytes as well as str, so `exec(f"import {name}".encode())`
# executes exactly the payload the f-string built.
_CONVERSIONS = ("encode", "decode")

# Constructors that hand the same source on in another type. Same argument as
# `_CONVERSIONS`, spelled as a call instead of a method: `bytes(s, "utf-8")` is
# documented as `s.encode("utf-8")`, `str(s)` on a str is the str, and `exec`
# compiles any of them. Verified on CPython 3.13: `exec(bytes(f"import {name}",
# "utf-8"))`, `exec(bytearray(...))` and `exec(memoryview(...))` all import.
_CONSTRUCTORS = ("bytes", "bytearray", "str", "memoryview")

# Each constructor also takes its source by keyword, verified on CPython 3.13:
# `bytes(source = ..., encoding = ...)` and `str(object = ...)` both build the same
# value a positional call would, so reading only `args[0]` missed them.
_CONSTRUCTOR_SOURCE_KEYWORD = {
    "bytes": "source",
    "bytearray": "source",
    "str": "object",
    "memoryview": "object",
}


def _constructor_name(function: ast.AST) -> str | None:
    """`bytes` for both `bytes(...)` and `builtins.bytes(...)`, else None."""
    if isinstance(function, ast.Name) and function.id in _CONSTRUCTORS:
        return function.id
    if isinstance(function, ast.Attribute) and function.attr in _CONSTRUCTORS:
        if isinstance(function.value, ast.Name) and function.value.id == "builtins":
            return function.attr
    return None


def _constructor_source(node: ast.Call, name: str) -> ast.AST | None:
    """The value a constructor is converting, positional or by keyword."""
    if node.args:
        return node.args[0]
    wanted = _CONSTRUCTOR_SOURCE_KEYWORD.get(name)
    for keyword in node.keywords:
        if keyword.arg == wanted:
            return keyword.value
    return None


def _is_interpolated(node: ast.AST, resolve = None) -> str | None:
    """Returns why `node` is a built string, or None if it is not one.

    `resolve` maps a bare name to the reason it is tainted, or None. It is passed
    at a sink and not while binding, so this stays one level of indirection: a
    name is resolved where it is executed, never chained into another binding.
    """
    # `exec(payload := f"import {name}")` executes the f-string; the walrus is an
    # `ast.NamedExpr` wrapper around it, not a different value.
    while isinstance(node, ast.NamedExpr):
        node = node.value
    if isinstance(node, ast.Starred):
        # `exec(*(f"import {name}",))` spreads a literal container, so the source is
        # right there. The source is always the FIRST element, because that is the
        # position it occupies in a normal call, so a longer container is read the same
        # way: `exec(*(f"import {name}", globals()))` and
        # `compile(*(f"x = {name}", "<x>", "exec"))` are ordinary calls that happen to
        # pass their later arguments through the same star. Requiring exactly one
        # element dropped both. A starred NAME is still left alone: nothing here knows
        # what it holds, and flagging every `exec(*args)` would be noise.
        inner = node.value
        if isinstance(inner, (ast.Tuple, ast.List)) and inner.elts:
            return _is_interpolated(inner.elts[0], resolve)
        return None
    if isinstance(node, ast.Name):
        return resolve(node.id) if resolve is not None else None
    if isinstance(node, ast.BoolOp):
        # `exec(enabled and f"import {name}")` executes the interpolated operand
        # whenever the guard lets it through: same conditional-source shape as IfExp.
        for operand in node.values:
            reason = _is_interpolated(operand, resolve)
            if reason is not None:
                return reason
        return None
    if isinstance(node, ast.IfExp):
        # `exec(f"import {name}" if flag else "import os")` executes whichever branch
        # is taken, so either one being built is enough.
        return _is_interpolated(node.body, resolve) or _is_interpolated(node.orelse, resolve)
    if isinstance(node, ast.JoinedStr):
        # An f-string with no placeholders is just a literal.
        if any(isinstance(v, ast.FormattedValue) for v in node.values):
            return "f-string"
        return None
    if isinstance(node, ast.BinOp):
        if isinstance(node.op, ast.Mod):
            return "%-format"
        if isinstance(node.op, ast.Add):
            return "string concatenation"
    if isinstance(node, ast.Call):
        function = node.func
        if isinstance(function, ast.Attribute):
            if function.attr in _BUILDERS:
                return f".{function.attr}()"
            if function.attr in _CONVERSIONS:
                # `str.encode(s)` is the unbound descriptor spelling of `s.encode()`.
                # There the source is the first argument and the receiver is the type,
                # so unwrapping the receiver looked at the name `str` and found nothing.
                # `str.encode(s)` and `builtins.str.encode(s)` alike: the receiver
                # names the type, so the source is the first argument.
                if _constructor_name(function.value) is not None:
                    return _is_interpolated(node.args[0], resolve) if node.args else None
                # Unwrap the receiver: the conversion changes the type, not the syntax.
                return _is_interpolated(function.value, resolve)
        constructor = _constructor_name(function)
        if constructor is not None:
            source = _constructor_source(node, constructor)
            if source is not None:
                return _is_interpolated(source, resolve)
        # `exec("import MODULE".replace("MODULE", name))` splices a value into a
        # template that is right there in the file, which is the `.format()` shape
        # spelled differently. Restricted to a literal receiver on purpose: the
        # `exec(inspect.getsource(f).replace(...))` idiom this repo is built on has a
        # variable receiver and is not this shape. Verified: adding plain "replace"
        # to _BUILDERS instead raises 5 findings here and 5 in unsloth, all of them
        # that idiom; this branch raises none.
        if isinstance(function, ast.Attribute) and function.attr == "replace":
            receiver = function.value
            if isinstance(receiver, ast.Constant):
                if isinstance(receiver.value, (str, bytes)):
                    return ".replace() on a literal"
            # `exec(f"import {model_type}".replace("-", "_"))` is the shape from the
            # original report with a normalisation step bolted on. The receiver is the
            # f-string itself, so recursing into it keeps that visible. This does not
            # catch the `exec(inspect.getsource(f).replace(...))` idiom, whose receiver
            # is a call that is not interpolated and yields None here.
            inner = _is_interpolated(receiver, resolve)
            if inner is not None:
                return inner
            # `str.replace(template, old, new)` is the unbound spelling; the template
            # is the first argument rather than the receiver.
            if _constructor_name(receiver) in ("str", "bytes"):
                if node.args:
                    template = node.args[0]
                    if isinstance(template, ast.Constant):
                        if isinstance(template.value, (str, bytes)):
                            return ".replace() on a literal"
                    # The template can be built rather than literal, same as for the
                    # bound spelling handled just above.
                    return _is_interpolated(template, resolve)
    return None


def _sink_name(function: ast.AST, aliases: dict | None = None) -> str | None:
    """The sink this call target names, if any.

    Both `exec(...)` and `builtins.exec(...)` execute. Matching only `ast.Name` meant
    the second form passed the lint with zero findings.

    `aliases` maps a local name to the sink it was imported as. `from builtins import
    exec as run` gives `run` the same builtin, so reading only the spelling at the call
    site missed it. Only names bound by an import from `builtins` are recorded, which
    keeps this to a fact stated in the file rather than a guess about what a name holds.
    """
    if isinstance(function, ast.Name):
        if function.id in SINKS:
            return function.id
        if aliases and function.id in aliases:
            return aliases[function.id]
    if isinstance(function, ast.Attribute) and function.attr in SINKS:
        if isinstance(function.value, ast.Name):
            module = function.value.id
            if module == "builtins" or (aliases or {}).get(f"module:{module}"):
                return f"builtins.{function.attr}"
    return None


def _source_argument(node: ast.Call, sink: str) -> ast.AST | None:
    """The source argument of a sink call, whether positional or by keyword.

    `exec` and `eval` take their source positional-only, so for those it is always
    `args[0]`. `compile` does not: its signature is
    `compile(source, filename, mode, ...)` with no `/`, so
    `compile(source = f"y = {x}", filename = "<x>", mode = "exec")` compiles exactly
    the same payload with `node.args` empty. Checking only `args[0]` meant that call
    was skipped entirely. `studio/backend/core/inference/tools.py` already resolves
    sink arguments this way.
    """
    if node.args:
        return node.args[0]
    if sink.rpartition(".")[2] == "compile":
        for keyword in node.keywords:
            if keyword.arg == "source":
                return keyword.value
    return None


class _Visitor(ast.NodeVisitor):
    def __init__(self, path: Path):
        self.path = path
        # Set for a notebook cell, so two cells defining the same function name are
        # separate allowlist entries rather than colliding on one key.
        self.qualname_prefix = ""
        # An annotation only runs at module or class scope, and only when the module
        # has not deferred annotations. Set by the caller from the parsed tree.
        self.annotations_deferred = False
        # Kind of each enclosing scope, innermost last. What decides whether an
        # annotation runs is the scope it sits in directly, not whether a function
        # appears anywhere above it.
        self.scope_kinds: list[str] = ["module"]
        self.scope: list[str] = []
        self.findings: list[dict] = []
        # name -> reason, for locals bound to a built string in the current scope.
        self.tainted: list[dict[str, str]] = [{}]
        # Local name -> the sink it names, for `from builtins import exec as run` and
        # `import builtins as b`. One flat map: an import binds for the whole module.
        self.sink_aliases: dict[str, str] = {}

    def _qualname(self) -> str:
        inner = ".".join(self.scope) if self.scope else "<module>"
        return f"{self.qualname_prefix}::{inner}" if self.qualname_prefix else inner

    def _outer_parts(self, node):
        """The pieces of a `def`/`class` that run in the *enclosing* scope.

        A definition statement is not one atomic thing. Decorators, default values,
        base classes and (unless deferred) parameter and return annotations are all
        evaluated where the `def` or `class` appears, before the new scope exists.
        Only the body runs later, in the new scope. Visiting the whole node inside the
        fresh taint map therefore lost real findings: `payload = f"import {user}"`
        followed by `def f(x = exec(payload)): ...` executes the built string at
        definition time, in the scope that built it.

        This is scope *accuracy*, not the taint-inheritance-into-nested-scopes idea
        that stays rejected: nothing here lets a name bound in one scope be trusted or
        distrusted in another. It only puts each expression in the scope that actually
        evaluates it.
        """
        parts = list(node.decorator_list)
        if isinstance(node, ast.ClassDef):
            parts.extend(node.bases)
            parts.extend(node.keywords)
            return parts
        args = node.args
        parts.extend(d for d in args.defaults)
        parts.extend(d for d in args.kw_defaults if d is not None)
        if not self.annotations_deferred:
            for arg in (
                *args.posonlyargs, *args.args, *args.kwonlyargs,
                args.vararg, args.kwarg,
            ):
                if arg is not None and arg.annotation is not None:
                    parts.append(arg.annotation)
            if node.returns is not None:
                parts.append(node.returns)
        return parts

    def _enter(self, node):
        # Evaluated in the scope we are still in, before the new one exists.
        for part in self._outer_parts(node):
            self.visit(part)

        self.scope.append(node.name)
        self.scope_kinds.append(
            "class" if isinstance(node, ast.ClassDef) else "function"
        )
        # A fresh scope: a name built in one function says nothing about the same name
        # in another.
        self.tainted.append({})
        for statement in node.body:
            self.visit(statement)
        self.tainted.pop()
        self.scope.pop()
        self.scope_kinds.pop()
        # The statement ends by binding its own name out here, to a function or a
        # class. Leaving the old entry in place reported
        # `payload = f"import {user}"; def payload(): pass; exec(payload)`, where the
        # sink can only ever be handed a function object. Unlike a conditional rebind
        # this one is unconditional: reaching the end of the statement means the name
        # was assigned.
        self.tainted[-1].pop(node.name, None)

    visit_FunctionDef = _enter
    visit_AsyncFunctionDef = _enter
    visit_ClassDef = _enter

    def visit_Assign(self, node: ast.Assign):
        """Tracks `payload = f"...{x}..."` so `exec(payload)` is still caught.

        One level of local indirection, which is all it took to defeat the previous
        version: moving the interpolation onto the line above is a two-line refactor
        that leaves the vulnerability shape exactly as it was. Rebinding a tracked name
        to something that is not a built string clears it, so this does not accumulate
        false positives.
        """
        reason = _is_interpolated(node.value)
        # Runtime order, not source order. The right hand side is evaluated first,
        # then the targets are assigned left to right, and a target that is not a
        # plain name has expressions of its own that run at its turn. So in
        # `payload = table[exec(payload)] = f"import {name}"` the f-string reaches
        # `payload` before the subscript is evaluated, and the `exec` sees it.
        # Visiting every target before binding any of them missed that.
        self.visit(node.value)
        for target in node.targets:
            self.visit(target)
            self._bind(target, reason)
            self._bind_unpacked(target, node.value)

    def visit_AnnAssign(self, node: ast.AnnAssign):
        """Same tracking for `payload: str = f"...{x}..."`.

        An annotated assignment is an `ast.AnnAssign`, a sibling of `ast.Assign`, and
        `NodeVisitor` dispatches on the exact class name - so `visit_Assign` never saw
        it and adding a type hint was enough to hide the binding. `node.value` is
        optional: a bare `payload: str` declares nothing and must leave taint alone
        rather than clear it.
        """
        reason = _is_interpolated(node.value) if node.value is not None else None
        if node.value is not None:
            self.visit(node.value)
            self._bind(node.target, reason)
        # The annotation is evaluated AFTER the store, so a runtime annotation
        # observes the new binding: `payload: exec(payload) = f"import {name}"`
        # executes the value that was just assigned. Confirmed on CPython 3.13.
        #
        # But only where the annotation runs at all. A function-local annotation is
        # never evaluated, and neither is a module or class one under
        # `from __future__ import annotations`. Visiting those unconditionally
        # reported code that cannot execute, which is a false CI failure rather than
        # a missed detection - verified both cases against the interpreter.
        if self._annotation_executes():
            self.visit(node.annotation)
        self.visit(node.target)

    def visit_AugAssign(self, node: ast.AugAssign):
        """`payload += anything` builds a string the same way `a + b` does.

        `_is_interpolated` reports a plain `a + b` as concatenation without caring what
        the operands are, so `payload += model_type` has to be treated the same way.
        Requiring the right hand side to be interpolated made
        `payload = "import "; payload += model_type; exec(payload)` pass while the
        one-line `exec("import " + model_type)` was caught, which is the same code.

        `%=` is the same argument in the other spelling: `_is_interpolated` already
        reports a binary `"import %s" % name` as `%-format`, and
        `payload = "import %s"; payload %= name` is that expression written as two
        statements. The remaining augmented operators do not build source out of a
        value, so they are left alone.
        """
        self.visit(node.value)
        if isinstance(node.op, (ast.Add, ast.Mod)):
            if isinstance(node.op, ast.Mod):
                reason, verb = "%-format", "applied"
            else:
                reason, verb = _is_interpolated(node.value) or "string concatenation", "appended"
            self._bind(node.target, f"{reason} {verb}")
        self.visit(node.target)

    def visit_For(self, node: ast.For):
        """`for payload in (f"import {name}",): exec(payload)` binds the same way.

        A loop target is a binding form like the assignments already tracked, and this
        one stays at the same level of indirection: only a literal tuple or list is
        looked into, so `for payload in build(): ...` reports nothing because nothing
        here knows what `build()` yields.

        A literal iterable also REBINDS: every element is statically visible, so if
        none of them is built then the target is clean afterwards no matter what it
        held before. Binding only on the interpolated elements left a stale reason on
        `payload = f"import {name}"; for payload in ("pass",): exec(payload)`, which
        executes the literal and nothing else. An empty literal never runs its body and
        never rebinds, so it clears nothing.
        """
        self.visit(node.iter)
        if isinstance(node.iter, (ast.Tuple, ast.List)) and node.iter.elts:
            reasons = [_is_interpolated(element) for element in node.iter.elts]
            self._bind(node.target, next((r for r in reasons if r is not None), None))
        self.visit(node.target)
        for statement in node.body + node.orelse:
            self.visit(statement)

    visit_AsyncFor = visit_For

    def visit_NamedExpr(self, node: ast.NamedExpr):
        """`(payload := f"import {name}")` as a statement, then `exec(payload)`.

        Unwrapping the walrus at the sink only helps when the named expression is
        handed straight to it. Standing on its own it is exactly the one level of
        local indirection already tracked for `payload = f"..."`, and it is a
        parenthesis away from that spelling, so it has to bind the same way.
        """
        self.generic_visit(node)
        self._bind(node.target, _is_interpolated(node.value))

    def _annotation_executes(self) -> bool:
        return not self.annotations_deferred and self.scope_kinds[-1] != "function"

    def _bind_unpacked(self, target: ast.AST, value: ast.AST) -> None:
        """`payload, ignored = f"import {name}", None` binds each element separately.

        `_is_interpolated` looks at the tuple as a whole and reports nothing, and
        `_bind` ignores a target that is not a Name, so unpacking hid the same one
        level of local indirection the tracking exists to cover. Only the shapes that
        line up element for element are paired; a starred target or a mismatched
        length is left alone rather than guessed at.
        """
        if not isinstance(target, (ast.Tuple, ast.List)):
            return
        if not isinstance(value, (ast.Tuple, ast.List)):
            return
        if len(target.elts) != len(value.elts):
            return
        if any(isinstance(e, ast.Starred) for e in target.elts + value.elts):
            return
        for element, item in zip(target.elts, value.elts):
            self._bind(element, _is_interpolated(item))
            self._bind_unpacked(element, item)

    def _bind(self, target: ast.AST, reason: str | None) -> None:
        if not isinstance(target, ast.Name):
            return
        if reason is None:
            self.tainted[-1].pop(target.id, None)
        else:
            self.tainted[-1][target.id] = f"{reason} via `{target.id}`"

    def visit_ImportFrom(self, node: ast.ImportFrom):
        """`from builtins import exec as run` makes `run` the same builtin."""
        if node.module == "builtins" and not node.level:
            for alias in node.names:
                if alias.name in SINKS:
                    self.sink_aliases[alias.asname or alias.name] = alias.name
        self.generic_visit(node)

    def visit_Import(self, node: ast.Import):
        """`import builtins as b` makes `b.exec` the same builtin."""
        for alias in node.names:
            if alias.name == "builtins" and alias.asname:
                self.sink_aliases[f"module:{alias.asname}"] = "builtins"
        self.generic_visit(node)

    def visit_Lambda(self, node: ast.Lambda):
        """A lambda parameter shadows the enclosing name for the body.

        `payload = f"import {name}"` followed by `run = lambda payload: exec(payload)`
        was reported although the sink can only ever see the argument the caller
        passes. The parameters are the part that is certainly shadowed, so only they
        are removed, and only for the body.

        Note what is deliberately NOT done here: the body still reads the enclosing map
        otherwise, because `lambda: exec(payload)` really does close over the outer
        `payload` and that is a true finding. Clearing the whole scope, as a `def`
        does, would trade this false positive for a false negative. The asymmetry with
        `_enter` is the existing documented limit on cross-scope taint, not something
        introduced here.
        """
        args = node.args
        for default in (*args.defaults, *(d for d in args.kw_defaults if d is not None)):
            self.visit(default)
        shadowed = {
            arg.arg
            for arg in (*args.posonlyargs, *args.args, *args.kwonlyargs,
                        args.vararg, args.kwarg)
            if arg is not None
        }
        saved = {name: self.tainted[-1].pop(name) for name in shadowed if name in self.tainted[-1]}
        self.visit(node.body)
        self.tainted[-1].update(saved)

    def visit_Call(self, node: ast.Call):
        sink = _sink_name(node.func, self.sink_aliases)
        argument = _source_argument(node, sink) if sink is not None else None
        if argument is not None:
            # The taint lookup has to happen wherever the unwrapping stops, not only
            # when the argument is a bare name: `payload = f"import {name}"` followed
            # by `exec(payload.encode())` executes the same bytes and used to unwrap
            # to an `ast.Name` that nothing then looked up.
            reason = _is_interpolated(argument, self.tainted[-1].get)
            if reason is not None:
                self.findings.append(
                    {
                        "path": _relative(self.path),
                        "qualname": self._qualname(),
                        "sink": sink,
                        "reason": reason,
                        "line": node.lineno,
                        "hash": _call_hash(node),
                    }
                )
        self.generic_visit(node)


def _call_hash(node: ast.Call) -> str:
    """Hashes the call, canonicalised through `ast.unparse`.

    Line numbers drift whenever anything above the call changes; the call itself does
    not. Unparsing means reindenting, rewrapping or reflowing the call does not
    invalidate a justification, while changing what is interpolated does.
    """
    return hashlib.sha256(ast.unparse(node).encode("utf-8")).hexdigest()[:16]


NOTEBOOK_SUFFIX = ".ipynb"


def _notebook_code_cells(path: Path) -> list[tuple[int, str]]:
    """(index, raw source) for each code cell, exactly as written."""
    try:
        raw = path.read_bytes()
    except OSError as error:
        # `.py` files return [] here, but a notebook named on the command line has been
        # asked for explicitly, and silently skipping it is the reduced coverage the
        # rest of this file exists to report.
        raise ScanError(
            f"{_relative(path)}: could not be read ({error.__class__.__name__}), so "
            f"its code cells were not checked"
        ) from None
    try:
        document = json.loads(raw.decode("utf-8", errors = "replace"))
    except (ValueError, UnicodeError) as error:
        raise ScanError(
            f"{_relative(path)}: could not be read as a notebook "
            f"({error.__class__.__name__}), so its code cells were not checked"
        ) from None
    cells = []
    for index, cell in enumerate(document.get("cells", [])):
        if cell.get("cell_type") != "code":
            continue
        source = cell.get("source", "")
        if isinstance(source, list):
            source = "".join(source)
        cells.append((index, source))
    return cells


# Line magics whose argument is ordinary Python, so replacing the whole line would
# throw away real code: `%time exec(payload)` executes exactly what it says.
_CODE_MAGICS = ("time", "timeit", "prun", "debug", "capture")


def _magic_argument(rest: str) -> str:
    """The Python part of a line magic's argument, with its options removed.

    `%timeit -n 1 exec(payload)` carries options before the code, and keeping the whole
    remainder left `-n 1 exec(...)`, which does not parse - so the cell was skipped and
    the sink went unread. Leading option tokens are dropped one at a time until what is
    left parses. Dropping only from the front, and only while the remainder still fails,
    means a genuine argument is never truncated.
    """
    candidate = rest.strip()
    after_option = False
    while candidate:
        try:
            ast.parse(candidate)
            return candidate
        except SyntaxError:
            head, separator, tail = candidate.partition(" ")
            if not separator:
                break
            if head.startswith("-"):
                # An option may carry a value of any shape: `%timeit -s "x=1" exec(...)`
                # leaves a quoted string at the front, which is not option-looking and
                # is not numeric, so the loop used to stop there and the whole cell was
                # skipped. One value per option is consumed, and only immediately after
                # the option that introduced it, so a genuine argument is still never
                # truncated.
                after_option = True
            elif after_option or head.lstrip("-").isdigit():
                after_option = False
            else:
                break
            candidate = tail.strip()
    return rest


# `out = !ls`, `files, err = !ls`, `t = %timeit -o f()`. IPython's capture syntax is an
# assignment whose right hand side is a magic or a shell escape, so the `!` or `%` is not
# at the start of the line and the plain check below never fired. Neither the raw text
# nor the neutralised text parsed, so the whole cell - including any sink after it - was
# skipped. The target list is restricted to names, attributes, subscripts and the commas
# and brackets that separate them, plus the quotes a subscript key needs, so
# `outputs["log"] = !printf hello` matches while an ordinary `x = y != z` cannot: the
# character class has no `=` in it, so the target can never span the assignment.
_CAPTURE = re.compile(r"""^(\s*)([\w.,()\[\]\s'"]+?)\s*=\s*([!%])(?!=)(.*)$""")


def _string_open_lines(source: str) -> frozenset:
    """Indices of physical lines that begin inside an unterminated string literal.

    Text inside a triple-quoted string is data, not code, and a line of it may well
    begin with `%` or `!`. Rewriting such a line to `pass` can delete the string's own
    closing delimiter, which turns a parseable cell into a skipped one and loses every
    sink below it. Scanning for the quote state first keeps the rewrite to real code.

    This is a scanner, not a tokenizer, because the input is by definition not valid
    Python - it is a cell with magics in it, which is why it reached this function at
    all. It handles escapes, comments and both quote characters; it is not asked to do
    more than decide, per line, "are we inside a triple-quoted string here".
    """
    inside = set()
    delimiter = ""
    index, line_number = 0, 0
    while index < len(source):
        character = source[index]
        if character == "\n":
            line_number += 1
            if delimiter:
                inside.add(line_number)
            index += 1
            continue
        if delimiter:
            if character == "\\":
                index += 2
                continue
            if source.startswith(delimiter, index):
                index += len(delimiter)
                delimiter = ""
                continue
            index += 1
            continue
        if character == "#":
            index = source.find("\n", index)
            if index == -1:
                break
            continue
        if character in "\"'":
            triple = source[index : index + 3]
            if triple in ('"""', "'''"):
                delimiter = triple
                index += 3
            else:
                # A single-quoted string cannot span lines except by continuation, and
                # a line inside one still is not a magic, so it is enough to skip it.
                delimiter = character
                index += 1
            continue
        index += 1
    return frozenset(inside)


def _neutralised(source: str) -> str:
    """The cell with IPython magics and shell escapes replaced by `pass`.

    A `%magic` becomes `pass` at the same indentation rather than a blank line, so a
    magic alone in an `if:` body does not leave an empty block. A `!cmd \\` continues
    onto the following physical lines, and those are blanked too - otherwise ordinary
    Python further down the same cell was thrown away with the shell command.
    """
    out, continuing = [], False
    in_string = _string_open_lines(source)
    for number, line in enumerate(source.splitlines()):
        if number in in_string:
            out.append(line)
            continuing = False
            continue
        capture = _CAPTURE.match(line)
        if capture:
            indent, target, operator, rest = capture.groups()
            magic = rest.split(maxsplit = 1)[0] if operator == "%" and rest.strip() else ""
            if magic in _CODE_MAGICS and rest.partition(" ")[2].strip():
                # `t = %timeit -o exec(payload)` captures a result, but IPython still
                # runs the Python argument. Replacing the whole line dropped the sink,
                # which is the same mistake the bare `%time exec(...)` handling already
                # fixed once.
                argument = _magic_argument(rest.partition(" ")[2])
                out.append(f"{indent}{target} = {argument}")
            else:
                # The shell or magic result is opaque, so binding None both keeps the
                # statement parseable and correctly leaves the target untracked.
                out.append(f"{indent}{target} = None")
            continuing = line.rstrip().endswith("\\")
            continue
        if continuing:
            out.append("")
            continuing = line.rstrip().endswith("\\")
            continue
        stripped = line.lstrip()
        if stripped.startswith(("%", "!")):
            indent = line[: len(line) - len(stripped)]
            # A line magic that takes code keeps its argument; the magic itself is not
            # Python but what follows it is, and dropping the line hid the sink.
            if stripped.startswith("%") and not stripped.startswith("%%"):
                magic, _, rest = stripped[1:].partition(" ")
                if magic in _CODE_MAGICS and rest.strip():
                    out.append(indent + _magic_argument(rest))
                    continuing = line.rstrip().endswith("\\")
                    continue
            out.append(indent + "pass")
            continuing = line.rstrip().endswith("\\")
        else:
            out.append(line)
    return "\n".join(out)


def _runs_python(argument: str) -> bool:
    """Whether a `%%script` argument names a Python interpreter.

    Options are skipped and the command is read off the front, so
    `%%script --no-raise-error python3` is recognised. Only the executable name is
    considered, which keeps `/usr/bin/python3.13` and a bare `python` on the same
    footing.
    """
    for token in argument.split():
        if token.startswith("-"):
            continue
        return token.rsplit("/", 1)[-1].split("\\")[-1].startswith("python")
    return False


def _foreign_cell_magic(code: str) -> str | None:
    """The `%%magic` name when it makes the whole cell stop being Python.

    `%%bash`, `%%sh`, `%%html`, `%%writefile` and friends mean every line below is
    another language, so failing to parse such a cell is the expected outcome rather
    than a gap in coverage - reporting it as "did not parse" only trained readers to
    ignore the notice. `%%time`, `%%capture` and the rest of `_CODE_MAGICS` are the
    opposite: the body is ordinary Python and must still be checked, so they are not
    foreign and only their first line is dropped.
    """
    for line in code.splitlines():
        if not line.strip():
            continue
        if not line.startswith("%%"):
            return None
        if not line[2:].strip():
            return None
        magic, _, argument = line[2:].strip().partition(" ")
        if magic in _CODE_MAGICS or magic in ("python", "python3"):
            return None
        if magic in ("script", "bash") and _runs_python(argument):
            # `%%script python` hands the body to a Python interpreter, so it is
            # Python and has to be scanned. Reading only the magic name classified it
            # as foreign and skipped the cell entirely.
            return None
        return magic
    return None


def _parse_cell(code: str, filename: str):
    """The cell's AST, trying it verbatim before neutralising anything.

    Parsing the raw text first matters: a line may begin with `%` and be an ordinary
    continuation of a modulo expression rather than a magic, and rewriting that to
    `pass` corrupted a cell that was valid Python to begin with. Only a cell that
    genuinely will not parse is put through `_neutralised`.
    """
    # Notebook prose regularly contains things like `\\(` in a regex written without a
    # raw string. That is the notebook author's business, not this gate's, and letting
    # the warning through buries the findings in noise.
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", SyntaxWarning)
        for candidate in (code, _neutralised(code)):
            try:
                return ast.parse(candidate, filename = filename)
            except (SyntaxError, ValueError):
                continue
    return None


def _scan_notebook(path: Path) -> list[dict]:
    """Findings across a notebook's code cells, which share one namespace.

    A single visitor spans the cells, because a notebook's cells run in order against
    the same globals: a payload built in one cell and executed in a later one is the
    natural way to write it, and a fresh visitor per cell threw that away. Only the
    qualname prefix changes per cell, so findings stay attributable.

    A cell that will not parse either way is SKIPPED, which is the opposite of what a
    `.py` file gets, and the difference is deliberate. A `.py` file claims to be a
    Python module, so failing to parse it means the gate did not check something it was
    supposed to. A notebook cell routinely is not Python at all. The count is printed
    so the gap stays visible rather than silent.
    """
    visitor = _Visitor(path)
    skipped = 0
    for index, code in _notebook_code_cells(path):
        if _foreign_cell_magic(code) is not None:
            # Positively identified as another language, so it is not an unchecked
            # Python cell and does not belong in the count.
            continue
        tree = _parse_cell(code, f"{path}#cell{index}")
        if tree is None:
            skipped += 1
            continue
        if _annotations_deferred(tree):
            visitor.annotations_deferred = True
        visitor.qualname_prefix = f"cell{index}"
        try:
            visitor.visit(tree)
        except RecursionError:
            raise ScanError(f"{_relative(path)}#cell{index}: too deeply nested to walk") from None
    if skipped:
        NOTEBOOK_SKIPPED.append((_relative(path), skipped))
    return visitor.findings


NOTEBOOK_SKIPPED: list[tuple[str, int]] = []


def _annotations_deferred(tree: ast.AST) -> bool:
    """True when the module carries `from __future__ import annotations`."""
    for node in getattr(tree, "body", []):
        if isinstance(node, ast.ImportFrom) and node.module == "__future__":
            if any(alias.name == "annotations" for alias in node.names):
                return True
    return False


def scan_file(path: Path) -> list[dict]:
    # A hard CI gate must not fall over on something that is not a readable file. A
    # dangling symlink, a directory named `*.py`, or a symlink to one all reach here
    # through rglob and raise out of read_text, failing the build for a reason that has
    # nothing to do with dynamic execution.
    if path.suffix == NOTEBOOK_SUFFIX:
        return _scan_notebook(path)
    try:
        # Bytes, not text. `ast.parse` applies the PEP 263 coding declaration itself,
        # while decoding here as UTF-8 with errors = "replace" corrupted any file that
        # declares another encoding. That was harmless while an unparseable file was
        # reported clean, but now that it fails the gate it turned a valid module into
        # a build failure: a latin-1 file with a non-ASCII identifier decoded to U+FFFD
        # and raised `invalid character`, even though py_compile accepts it.
        source = path.read_bytes()
    except OSError:
        return []
    try:
        tree = ast.parse(source, filename = str(path))
    except (SyntaxError, ValueError) as error:
        # A file that cannot be parsed has not been checked, and reporting it as clean
        # is the same bypass as swallowing a RecursionError. The comment here used to
        # defer to compileall in the same job, but both syntax-reporting steps in
        # lint-ci.yml are `continue-on-error: true`, so nothing else fails the build.
        # ValueError covers a source containing a NUL byte, which ast.parse rejects
        # separately from a syntax error.
        raise ScanError(
            f"{_relative(path)}: could not be parsed ({error.__class__.__name__}), so "
            f"it was not checked for interpolated dynamic execution"
        ) from None
    visitor = _Visitor(path)
    visitor.annotations_deferred = _annotations_deferred(tree)
    try:
        visitor.visit(tree)
    except RecursionError:
        # A deeply nested expression can exhaust the stack during the walk, after parse
        # succeeded. Returning [] here reported the file as clean, which is a bypass:
        # 500 nested `not` in front of an interpolated exec compiled fine and the gate
        # passed with zero findings. An unfinishable walk is an unknown, and a security
        # gate reports an unknown as a failure, not as a pass.
        raise ScanError(
            f"{_relative(path)}: too deeply nested to walk, so this file could not be "
            f"checked for interpolated dynamic execution"
        ) from None
    return visitor.findings


def scan(paths: list[Path]) -> tuple[list[dict], list[str]]:
    """Findings, plus the files the checker could not finish. Both fail the gate."""
    findings, errors = [], []
    for path in sorted(paths):
        try:
            findings.extend(scan_file(path))
        except ScanError as error:
            errors.append(str(error))
    return findings, errors


def collect_paths(targets: list[str]) -> tuple[list[Path], list[str]]:
    """Files to scan, plus the targets that resolved to nothing.

    A target that is neither a Python file nor a directory used to be dropped in
    silence, so renaming a file in `DEFAULT_TARGETS` or mistyping a `--paths`
    argument left the gate passing over less code than it claims to cover. Reduced
    coverage that still exits 0 is the failure this whole checker exists to avoid,
    so an unresolvable target is reported rather than skipped.
    """
    paths, missing = [], []
    for target in targets:
        root = REPO_ROOT / target
        if root.is_file() and root.suffix in (".py", NOTEBOOK_SUFFIX):
            paths.append(root)
        elif root.is_dir():
            # `is_file()` on each hit, so a directory named `foo.py` and a symlink that
            # points at one are skipped rather than read.
            before = len(paths)
            for pattern in ("*.py", f"*{NOTEBOOK_SUFFIX}"):
                paths.extend(
                    p
                    for p in root.rglob(pattern)
                    if p.is_file() and "tests" not in _exclusion_parts(p, root)
                )
            if len(paths) == before:
                # An existing but empty directory resolved "successfully" while
                # contributing nothing, which is the same reduced coverage a missing
                # target gives and was the one way left to exit 0 having checked
                # nothing.
                missing.append(
                    f"{target}: scan target contains no Python files or notebooks, "
                    f"so nothing under it was checked"
                )
        else:
            missing.append(
                f"{target}: requested scan target does not exist, so nothing under it was checked"
            )
    return paths, missing


def _exclusion_parts(path: Path, root: Path) -> tuple[str, ...]:
    """Path components the tests exclusion is matched against.

    Repo-relative when the file is in the repo, so the default scan keeps excluding
    `<target>/tests/...` exactly as before. A directory passed through `--paths` may
    sit outside the checkout - a pytest tmp_path, a vendored tree - and
    `relative_to(REPO_ROOT)` raises `ValueError` for every file under it, which took
    the whole run down with a traceback before any finding was printed. External
    single files already worked, so this only makes directories agree with them.
    """
    for base in (REPO_ROOT, root):
        try:
            return path.relative_to(base).parts
        except ValueError:
            continue
    return path.parts


def load_allowlist() -> dict[str, dict]:
    if not ALLOWLIST_PATH.exists():
        return {}
    data = json.loads(ALLOWLIST_PATH.read_text(encoding = "utf-8"))
    return {key_of(entry): entry for entry in data.get("allowed", [])}


def key_of(finding: dict) -> str:
    """Identity of a reviewed call: where it is, and what it is.

    The hash alone is not an identity. Two different call sites with byte-identical
    source share a hash, so approving one approved the other, and copying an
    allowlisted call into a function with attacker-controlled inputs inherited its
    justification without review. The location is half of what was reviewed, so it is
    half of the key.
    """
    return f"{finding['path']}::{finding['qualname']}::{finding['hash']}"


def write_allowlist(findings: list[dict], reason: str) -> None:
    existing = load_allowlist()
    allowed = []
    for finding in findings:
        previous = existing.get(key_of(finding), {})
        allowed.append(
            {
                "path": finding["path"],
                "qualname": finding["qualname"],
                "sink": finding["sink"],
                "kind": finding["reason"],
                "hash": finding["hash"],
                "reason": previous.get("reason", reason),
            }
        )
    allowed.sort(key = lambda e: (e["path"], e["qualname"], e["hash"]))
    ALLOWLIST_PATH.write_text(
        json.dumps(
            {
                "_comment": (
                    "Reviewed exec/eval/compile calls whose first argument is a built "
                    "string. Keyed on a hash of the call's own source, so editing the "
                    "call requires re-reviewing it. Regenerate with "
                    "scripts/lint_dynamic_exec.py --update, then replace every REVIEW "
                    "ME with why the interpolated value cannot be attacker controlled."
                ),
                "allowed": allowed,
            },
            indent = 2,
        )
        + "\n"
    )


# --- self test ---------------------------------------------------------------

_BAD = """
def f(model_type):
    exec(f"import transformers.models.{model_type}")
    eval("torch." + name)
    compile("x = %s" % value, "<x>", "exec")
    exec("a.{}.b".format(name))
    compile(source = f"y = {value}", filename = "<x>", mode = "exec")
    exec("import {module}".format_map(values))
    exec(f"import {name}".encode())
    annotated: str = f"import {name}"
    exec(annotated)
    exec(bytes(f"import {name}", "utf-8"))
    exec(payload := f"import {name}")
    exec("import MODULE".replace("MODULE", name))

def g(name):
    payload = f"import {name}"
    exec(payload.encode())

def h(name):
    payload = f"import {name}"
    payload: object = exec(payload)

def i(name):
    payload = f"import {name}"
    payload = exec(payload)

def j(name):
    (payload := f"import {name}")
    exec(payload)

def n(name, enabled):
    exec(enabled and f"import {name}")
    payload, ignored = f"import {name}", None
    exec(payload)
    exec(builtins.str.encode(f"import {name}"))

class Outer:
    inner_annotation: exec(f"import {NAME}") = 1

def m(model_type):
    payload = "import "
    payload += model_type
    exec(payload)

def k(name):
    table = {}
    payload = table[exec(payload)] = f"import {name}"

def l(name):
    exec(bytes(source = f"import {name}", encoding = "utf-8"))
    exec(str(object = f"import {name}"))
    exec(str.encode(f"import {name}"))

annotated_at_module: exec(annotated_at_module) = f"import {NAME}"
"""

_GOOD = """
import inspect

def f(cls):
    source = inspect.getsource(cls)
    exec(source, globals())
    eval(compile(source, "<x>", "eval"))
    exec(f"plain f-string with no placeholders")
    module.exec(f"{name}")          # not the builtin
    exec()                          # no arguments
    exec(source.replace("def a", "def b"), globals())   # variable receiver
    exec(str(source))               # str() of a name is not interpolation
"""


def self_test() -> int:
    import tempfile

    failures = []
    with tempfile.TemporaryDirectory() as directory:
        bad = Path(directory) / "bad.py"
        bad.write_text(_BAD)
        findings = scan_file(bad)
        kinds = sorted(f["reason"] for f in findings)
        expected = [
            "%-format",
            ".format()",
            ".format_map()",
            ".replace() on a literal",
            "f-string",
            "f-string",
            "f-string",
            "f-string",
            "f-string",
            "f-string",
            "f-string",
            "f-string",
            "f-string",
            "f-string",
            "f-string",
            "f-string via `annotated_at_module`",
            "f-string via `annotated`",
            "f-string via `payload`",
            "f-string via `payload`",
            "f-string via `payload`",
            "f-string via `payload`",
            "f-string via `payload`",
            "f-string via `payload`",
            "string concatenation",
            "string concatenation appended via `payload`",
        ]
        if kinds != expected:
            failures.append(f"expected {expected}, got {kinds}")
        if any(
            f["qualname"] not in ("f", "g", "h", "i", "j", "k", "l", "m", "n", "Outer", "<module>")
            for f in findings
        ):
            failures.append(f"qualname wrong: {[f['qualname'] for f in findings]}")

        good = Path(directory) / "good.py"
        good.write_text(_GOOD)
        clean = scan_file(good)
        if clean:
            failures.append(f"false positives: {clean}")

        # The hash must ignore reformatting but not a changed interpolation.
        one = Path(directory) / "one.py"
        one.write_text('def f(x):\n    exec(f"import {x}")\n')
        two = Path(directory) / "two.py"
        two.write_text('def f(x):\n    exec(\n        f"import {x}"\n    )\n')
        three = Path(directory) / "three.py"
        three.write_text('def f(x):\n    exec(f"import os; {x}")\n')
        h1 = scan_file(one)[0]["hash"]
        h2 = scan_file(two)[0]["hash"]
        h3 = scan_file(three)[0]["hash"]
        if h1 != h2:
            failures.append("reformatting changed the hash")
        if h1 == h3:
            failures.append("changing the interpolation did not change the hash")

        # An AST too deep to walk must fail the gate, not report the file clean.
        deep = Path(directory) / "deep.py"
        deep.write_text(
            "def f(user):\n    x = " + "not " * 500 + 'True\n    exec(f"import {user}")\n'
        )
        try:
            scan_file(deep)
            failures.append("a file too deep to walk was reported clean")
        except ScanError:
            pass
        _, errors = scan([deep])
        if len(errors) != 1:
            failures.append(f"scan() should surface the unscannable file, got {errors}")

        # A directory outside the repo must scan rather than crash on relative_to.
        external = Path(directory) / "external"
        external.mkdir()
        (external / "x.py").write_text('def f(m):\n    exec(f"import {m}")\n')
        collected, missing = collect_paths([str(external)])
        found, errors = scan(collected)
        errors += missing
        if len(found) != 1 or errors:
            failures.append(f"external directory not scanned: {found}, {errors}")

        # A file that cannot be parsed has not been checked, so it must not read as
        # clean. Both syntax-reporting steps in lint-ci.yml are continue-on-error, so
        # nothing else in the job would fail the build for it.
        broken = Path(directory) / "broken.py"
        broken.write_text("def f(:\n")
        try:
            scan_file(broken)
            failures.append("a file that does not parse was reported clean")
        except ScanError:
            pass

        # A file declaring a non-UTF-8 encoding is valid Python and must not fail the
        # gate. Decoding it as UTF-8 with errors = "replace" turned a latin-1
        # identifier into U+FFFD and made a good module unscannable.
        latin1 = Path(directory) / "latin1.py"
        latin1.write_bytes("# -*- coding: latin-1 -*-\ncaf\xe9 = 1\n".encode("latin-1"))
        try:
            if scan_file(latin1) != []:
                failures.append("the latin-1 file produced findings it should not have")
        except ScanError:
            failures.append("a valid latin-1 module was reported unscannable")

        # ast.parse rejects a NUL byte with ValueError rather than SyntaxError.
        nul = Path(directory) / "nul.py"
        nul.write_bytes(b"x = 1\x00\n")
        try:
            scan_file(nul)
            failures.append("a file containing a NUL byte was reported clean")
        except ScanError:
            pass

        # An annotation that cannot execute must not be reported. A function-local
        # annotation is never evaluated, and neither is a module one under
        # `from __future__ import annotations`.
        for name, body in (
            ("inert_local.py", 'def f(name):\n    x: exec(f"import {name}") = 1\n'),
            (
                "inert_future.py",
                'from __future__ import annotations\nname = "os"\ny: exec(f"import {name}") = 1\n',
            ),
        ):
            inert = Path(directory) / name
            inert.write_text(body)
            if scan_file(inert):
                failures.append(f"{name}: reported an annotation that never runs")
        # ... while the module-scope one that does run is still reported.
        live = Path(directory) / "live_annotation.py"
        live.write_text('name = "os"\npayload: exec(payload) = f"import {name}"\n')
        if not scan_file(live):
            failures.append("a module-scope runtime annotation was not reported")

        # A notebook's cells share one namespace, and a `%`-leading continuation of a
        # modulo expression is not a magic.
        import json as _json

        def _nb(cells):
            return _json.dumps(
                {
                    "cells": [{"cell_type": "code", "source": c} for c in cells],
                    "metadata": {},
                    "nbformat": 4,
                    "nbformat_minor": 5,
                }
            )

        for name, cells in (
            # payload built in one cell, executed in the next
            (
                "cross.ipynb",
                [['name = "os"\n', 'payload = f"import {name}"\n'], ["exec(payload)\n"]],
            ),
            # a continuation line starting with `%` is modulo, not a magic
            ("modulo.ipynb", [['name = "os"\n', 'exec("import %s"\n', "     % name)\n"]]),
            # ordinary Python after a multi-line shell command must still be read
            (
                "mixed.ipynb",
                [
                    [
                        "!pip install x \\\n",
                        "  --quiet\n",
                        'name = "os"\n',
                        'exec(f"import {name}")\n',
                    ]
                ],
            ),
        ):
            notebook = Path(directory) / name
            notebook.write_text(_nb(cells))
            if not scan_file(notebook):
                failures.append(f"{name}: notebook payload was not reported")

        # An existing but empty directory is reduced coverage, not a clean run.
        hollow = Path(directory) / "hollow"
        hollow.mkdir()
        _, nothing = collect_paths([str(hollow)])
        if len(nothing) != 1:
            failures.append(f"an empty scan directory was accepted: {nothing}")

        # A target that resolves to nothing means reduced coverage, not a clean run.
        _, absent = collect_paths(["no_such_target_xyz.py"])
        if len(absent) != 1:
            failures.append(f"a missing scan target was skipped in silence: {absent}")
        _, present = collect_paths([str(external)])
        if present:
            failures.append(f"an existing target was reported missing: {present}")

    for failure in failures:
        print(f"self-test: {failure}", file = sys.stderr)
    if failures:
        print(f"FAIL: {len(failures)} self-test failure(s)", file = sys.stderr)
        return 1
    print("self-test: ok")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description = __doc__)
    parser.add_argument("--self-test", action = "store_true")
    parser.add_argument(
        "--update", action = "store_true", help = "rewrite the allowlist from the current tree"
    )
    parser.add_argument(
        "--paths",
        nargs = "*",
        default = None,
        help = "files or directories to scan (default: the package)",
    )
    args = parser.parse_args()

    if args.self_test:
        return self_test()

    targets = args.paths if args.paths else list(DEFAULT_TARGETS)
    collected, missing = collect_paths(targets)
    findings, errors = scan(collected)
    # A target that resolved to nothing is reported with the unscannable files: in
    # both cases the gate looked at less code than it was asked to.
    errors += missing

    if args.update:
        # An allowlist written from an incomplete scan would bake in the gap.
        if errors:
            for error in errors:
                print(f"scan error: {error}", file = sys.stderr)
            print(
                "\nFAIL: refusing to rewrite the allowlist from an incomplete scan.",
                file = sys.stderr,
            )
            return 1
        write_allowlist(findings, reason = "REVIEW ME")
        print(f"wrote {len(findings)} entries to {ALLOWLIST_PATH.name}")
        return 0

    allowlist = load_allowlist()
    unreviewed = [f for f in findings if key_of(f) not in allowlist]
    pending = [
        entry
        for entry in allowlist.values()
        if entry.get("reason", "").strip().upper() in ("", "REVIEW ME")
    ]
    # Staleness is only meaningful over the whole tree: with --paths the scan is a
    # subset, so every entry outside it would look stale.
    seen = {key_of(f) for f in findings}
    stale = [] if args.paths else [entry for key, entry in allowlist.items() if key not in seen]

    for finding in unreviewed:
        print(
            f"{finding['path']}:{finding['line']}: {finding['sink']}() is handed a "
            f"{finding['reason']} (in {finding['qualname']})",
            file = sys.stderr,
        )
    for entry in pending:
        print(
            f"{entry['path']}: {entry['sink']}() in {entry['qualname']} is allowlisted "
            f"but has no justification",
            file = sys.stderr,
        )
    for entry in stale:
        print(
            f"{entry['path']}: allowlist entry for {entry['sink']}() in "
            f"{entry['qualname']} no longer matches any call - re-run --update",
            file = sys.stderr,
        )
    for error in errors:
        print(f"scan error: {error}", file = sys.stderr)
    for notebook, count in NOTEBOOK_SKIPPED:
        print(
            f"note: {notebook}: {count} code cell(s) did not parse and were not "
            f"checked (shell or partial cells)",
            file = sys.stderr,
        )

    if unreviewed or pending or stale or errors:
        print(
            f"\nFAIL: {len(unreviewed)} unreviewed, {len(pending)} unjustified, "
            f"{len(stale)} stale, {len(errors)} unscannable.\n"
            f"Fix the call, or run --update and write down why the interpolated value "
            f"cannot be attacker controlled.",
            file = sys.stderr,
        )
        return 1

    print(f"ok: {len(findings)} interpolated dynamic-execution call(s), all reviewed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
